const fs = require("fs");
const path = require("path");
const root = "server/lib/autoposter";

function w(name, lines) {
  const p = path.join(root, name);
  fs.writeFileSync(p, lines.join("\n") + "\n", "utf8");
  console.log("wrote", p);
}

w("discovery-core.js", [
  "const fs = require('fs');",
  "const path = require('path');",
  "const crypto = require('crypto');",
  "const DATA_DIR = path.join(__dirname, '..', '..', 'data', 'x');",
  "const SITE_URL = process.env.SITE_URL || 'https://gatorvaultinsider.com';",
  "function discoveryEnabled() { return process.env.X_AUTOPOST_DISCOVERY_ENABLED !== 'false'; }",
  "function readJson(filePath, fallback) { try { return JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch { return fallback; } }",
  "function writeJson(filePath, data) { fs.mkdirSync(path.dirname(filePath), { recursive: true }); fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8'); }",
  "function fpHash(input) { return crypto.createHash('sha256').update(String(input || '')).digest('hex').slice(0, 16); }",
  "function stripHtml(text) { return String(text || '').replace(/<[^>]+>/g, ' ').replace(/\\s+/g, ' ').trim(); }",
  "function newsCandidateFromBuilt(built, extra = {}) {",
  "  if (!built?.text) return null;",
  "  return { text: built.text, category: 'news', topic: extra.topic || 'recruiting', urgencyLabel: extra.urgencyLabel || 'major_beat',",
  "    postUrgency: extra.postUrgency || null, triggerType: extra.triggerType || null, teamEventType: extra.teamEventType || null,",
  "    programNewsType: extra.programNewsType || null, sourceEventType: extra.sourceEventType || null,",
  "    sources: extra.sources || [{ label: 'GatorVault', url: SITE_URL }], source: extra.source || 'auto:discovery',",
  "    intelFingerprint: extra.intelFingerprint || null, playerName: built.playerName || extra.playerName || null,",
  "    playerSlug: built.playerSlug || extra.playerSlug || null, sourceEventCreatedAt: extra.sourceEventCreatedAt || new Date().toISOString(),",
  "    sourcePublishedAt: extra.sourcePublishedAt || extra.sourceEventCreatedAt || null, identityConfirmed: extra.identityConfirmed || false,",
  "    validationMeta: { ...(built.validationMeta || {}), ...(extra.validationMeta || {}) }, templateBlocks: built.templateBlocks || null,",
  "    playerContext: built.playerContext || null };",
  "}",
  "module.exports = { DATA_DIR, SITE_URL, discoveryEnabled, readJson, writeJson, fpHash, stripHtml, newsCandidateFromBuilt };"
]);

w("discovery-uf-official.js", [
  "/**",
  " * UF Official discovery — any FloridaGators.com football news (broad capture).",
  " * Sources: football RSS + /sports/football page. Non-football sports excluded.",
  " */",
  "const path = require('path');",
  "const fetch = require('node-fetch');",
  "const { parseRssItems } = require('../rss-parse');",
  "const { intelFingerprint } = require('../commit-fingerprint');",
  "const { DATA_DIR, readJson, writeJson, fpHash, stripHtml, newsCandidateFromBuilt } = require('./discovery-core');",
  "const UF_OFFICIAL_SNAPSHOT_PATH = path.join(DATA_DIR, 'uf-official-news-snapshot.json');",
  "const UF_FOOTBALL_RSS = process.env.X_AUTOPOST_UF_OFFICIAL_RSS || 'https://floridagators.com/rss.aspx?path=football';",
  "const UF_FOOTBALL_NEWS_PAGE = process.env.X_AUTOPOST_UF_OFFICIAL_PAGE || 'https://floridagators.com/sports/football';",
  "const NON_FOOTBALL_SPORT_RES = [",
  "  /\\b(basketball|baseball|softball|soccer|volleyball|gymnastics|track and field|swimming|tennis|lacrosse|wrestling|gator basketball)\\b/i,",
  "  /\\/(basketball|baseball|softball|soccer|volleyball|gymnastics|track-and-field|swimming|tennis|lacrosse|wrestling)-/i",
  "];",
  "const FOOTBALL_SIGNAL_RES = [",
  "  /\\/football[-/]|path=football|\\/sports\\/football/i,",
  "  /\\b(football|gatorsfb|the swamp|sec football|quarterback|running back|wide receiver|touchdown|spring game|depth chart|coordinator|offensive line|defensive line|hall of fame|hof|recruiting|roster|spring practice|media day|game day|orange and blue)\\b/i",
  "];",
  "function slugToTitle(slug) {",
  "  return String(slug || '').split('-').filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');",
  "}",
  "function isUfOfficialFootballItem(item) {",
  "  if (process.env.X_AUTOPOST_UF_OFFICIAL_FOOTBALL_ONLY === 'false') return true;",
  "  if (item?._fromFootballPage || item?._fromFootballRss) return true;",
  "  const link = String(item?.link || '').toLowerCase();",
  "  const title = String(item?.title || '').toLowerCase();",
  "  const summary = String(item?.summary || item?.description || '').toLowerCase();",
  "  const combined = `${link} ${title} ${summary}`;",
  "  if (NON_FOOTBALL_SPORT_RES.some((re) => re.test(combined))) return false;",
  "  return FOOTBALL_SIGNAL_RES.some((re) => re.test(combined));",
  "}",
  "function parseNewsDateFromPath(link) {",
  "  const m = String(link || '').match(/\\/news\\/(\\d{4})\\/(\\d{1,2})\\/(\\d{1,2})\\//);",
  "  if (!m) return new Date().toISOString();",
  "  const iso = `${m[1]}-${String(m[2]).padStart(2, '0')}-${String(m[3]).padStart(2, '0')}T12:00:00.000Z`;",
  "  const ts = new Date(iso).getTime();",
  "  return Number.isFinite(ts) ? new Date(ts).toISOString() : new Date().toISOString();",
  "}",
  "async function fetchUfOfficialHtmlItems(limit = 12) {",
  "  const res = await fetch(UF_FOOTBALL_NEWS_PAGE, { timeout: 20000, headers: { 'User-Agent': 'GatorVaultAutoposter/1.0', Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' } });",
  "  if (!res.ok) throw new Error('UF news page HTTP ' + res.status);",
  "  const html = await res.text();",
  "  const items = [];",
  "  const seen = new Set();",
  "  const blockRe = /<article[^>]*class=\"[^\"]*c-stories__item[^\"]*\"[\\s\\S]*?<\\/article>/gi;",
  "  const blocks = html.match(blockRe) || [];",
  "  for (const block of blocks) {",
  "    if (items.length >= limit) break;",
  "    const linkMatch = block.match(/href=\"(\\/news\\/[^\"]+)\"/i);",
  "    if (!linkMatch) continue;",
  "    const link = linkMatch[1].startsWith('http') ? linkMatch[1] : `https://floridagators.com${linkMatch[1]}`;",
  "    if (seen.has(link)) continue;",
  "    seen.add(link);",
  "    const titleMatch = block.match(/<h3[^>]*>([\\s\\S]*?)<\\/h3>/i) || block.match(/<a[^>]+class=\"[^\"]*c-stories__headline[^\"]*\"[^>]*>([\\s\\S]*?)<\\/a>/i);",
  "    const title = stripHtml(titleMatch?.[1] || slugToTitle(link.split('/').pop()));",
  "    if (!title) continue;",
  "    items.push({ title, link, summary: '', pubDate: parseNewsDateFromPath(link), _fromFootballPage: true });",
  "  }",
  "  if (items.length) return items;",
  "  const linkRe = /href=\"(\\/news\\/\\d{4}\\/\\d{1,2}\\/\\d{1,2}\\/[^\"]+)\"/gi;",
  "  let match;",
  "  while ((match = linkRe.exec(html)) && items.length < limit) {",
  "    const link = `https://floridagators.com${match[1]}`;",
  "    if (seen.has(link)) continue;",
  "    seen.add(link);",
  "    items.push({ title: slugToTitle(match[1].split('/').pop()), link, summary: '', pubDate: parseNewsDateFromPath(link), _fromFootballPage: true });",
  "  }",
  "  return items;",
  "}",
  "async function fetchUfOfficialRssItems(limit = 12) {",
  "  const res = await fetch(UF_FOOTBALL_RSS, { timeout: 20000, headers: { 'User-Agent': 'GatorVaultAutoposter/1.0', Accept: 'application/rss+xml, application/xml, text/xml, */*' } });",
  "  if (!res.ok) throw new Error('UF RSS HTTP ' + res.status);",
  "  const xml = await res.text();",
  "  if (!xml || !xml.trim()) return [];",
  "  return parseRssItems(xml, limit).map((row) => ({ ...row, _fromFootballRss: true }));",
  "}",
  "async function fetchUfOfficialNewsItems(limit = 12) {",
  "  let items = [];",
  "  try { items = await fetchUfOfficialRssItems(limit); } catch (err) { console.warn('[discovery] UF official RSS failed:', err.message); }",
  "  if (!items.length) {",
  "    try { items = await fetchUfOfficialHtmlItems(limit); } catch (err) { console.warn('[discovery] UF official HTML fallback failed:', err.message); }",
  "  }",
  "  return items;",
  "}",
  "async function buildCandidateFromUfOfficialItem(item) {",
  "  const { decodeEntities } = require('../rss-parse');",
  "  const title = decodeEntities(stripHtml(item.title));",
  "  const summary = decodeEntities(stripHtml(item.summary || item.description || ''));",
  "  if (!title) return null;",
  "  const beatText = summary ? (title + ' — ' + summary).slice(0, 280) : title;",
  "  const synthetic = { handle: 'GatorsFB', writerName: 'Florida Gators', outlet: 'UF Official', text: beatText, publishedAt: item.pubDate || item.published || new Date().toISOString(), url: item.link || 'https://floridagators.com/sports/football' };",
  "  const copy = require('../x-autoposter-copy');",
  "  const prefilter = require('../beat-intel-prefilter');",
  "  const combined = title + ' ' + summary;",
  "  const teamEventType = prefilter.classifyTeamEventType(combined);",
  "  const programNewsType = prefilter.classifyProgramNewsType(combined) || 'program_update';",
  "  let built = null;",
  "  if (teamEventType) {",
  "    built = await copy.buildTeamEventCopyAsync(synthetic, { triggerType: 'team_event', teamEventType });",
  "  } else {",
  "    built = await copy.buildProgramNewsCopyAsync(synthetic, { triggerType: 'program_news', programNewsType });",
  "  }",
  "  if (!built?.text || built.skipReason) return null;",
  "  const isProgram = built.triggerType === 'program_news' || teamEventType == null;",
  "  return newsCandidateFromBuilt(built, { topic: isProgram ? 'program' : 'team', urgencyLabel: isProgram ? 'breaking' : 'major_beat', postUrgency: isProgram ? 'breaking' : null, triggerType: isProgram ? 'program_news' : 'team_event', programNewsType: isProgram ? programNewsType : null, teamEventType: isProgram ? null : teamEventType, sourceEventType: isProgram ? 'program_news' : 'team_event', sources: [{ label: 'Florida Gators', url: synthetic.url }], source: 'auto:uf-official-news', intelFingerprint: intelFingerprint(item.link || title, 'uf_official_news', synthetic.publishedAt), sourceEventCreatedAt: synthetic.publishedAt, sourcePublishedAt: synthetic.publishedAt, identityConfirmed: true, validationMeta: { programNews: true, ufOfficialFootball: true, eliteCompose: true, officialHeadline: title } });",
  "}",
  "async function collectUfOfficialNewsCandidates({ forcePost = false, limit } = {}) {",
  "  if (process.env.X_AUTOPOST_UF_OFFICIAL_NEWS === 'false') return [];",
  "  const maxItems = limit || parseInt(process.env.X_AUTOPOST_UF_OFFICIAL_LIMIT || (forcePost ? '12' : '8'), 10);",
  "  const snapshot = readJson(UF_OFFICIAL_SNAPSHOT_PATH, { fingerprints: {} });",
  "  let items = [];",
  "  try { items = await fetchUfOfficialNewsItems(maxItems); } catch (err) { console.warn('[discovery] UF official news failed:', err.message); return []; }",
  "  const candidates = [];",
  "  for (const item of items) {",
  "    if (!isUfOfficialFootballItem(item)) continue;",
  "    const hash = fpHash(item.link || item.title);",
  "    if (!forcePost && snapshot.fingerprints[hash]) continue;",
  "    const row = await buildCandidateFromUfOfficialItem(item);",
  "    if (row) { candidates.push(row); snapshot.fingerprints[hash] = new Date().toISOString(); }",
  "  }",
  "  if (candidates.length) { snapshot.lastRun = new Date().toISOString(); writeJson(UF_OFFICIAL_SNAPSHOT_PATH, snapshot); }",
  "  return candidates;",
  "}",
  "module.exports = { UF_OFFICIAL_SNAPSHOT_PATH, isUfOfficialFootballItem, fetchUfOfficialNewsItems, collectUfOfficialNewsCandidates };"
]);

w("discovery-index.js", [
  "/**",
  " * Autoposter Phase 2 — aggregate discovery collectors.",
  " */",
  "const { discoveryEnabled } = require('./discovery-core');",
  "const ufOfficial = require('./discovery-uf-official');",
  "const roster = require('./discovery-roster');",
  "const scouting = require('./discovery-scouting');",
  "const gameZone = require('./discovery-game-zone');",
  "const heat = require('./discovery-heat');",
  "",
  "async function collectAllDiscoveryCandidates(opts = {}) {",
  "  if (!discoveryEnabled()) return [];",
  "  const widen = !!(opts.forcePost || opts.digDeeper);",
  "  const merged = [];",
  "  const ufLimit = parseInt(process.env.X_AUTOPOST_UF_OFFICIAL_LIMIT || (widen ? '12' : '8'), 10);",
  "  const runs = [",
  "    () => ufOfficial.collectUfOfficialNewsCandidates({ forcePost: widen, limit: ufLimit }),",
  "    () => roster.collectRosterDeltaCandidates(),",
  "    () => scouting.collectScoutingUpdateCandidates(),",
  "    () => gameZone.collectGameZoneCandidates(),",
  "    () => heat.collectHeatMoverCandidates({ limit: widen ? 8 : 5 }),",
  "  ];",
  "  for (const run of runs) {",
  "    try {",
  "      for (const row of await run()) merged.push(row);",
  "    } catch (err) {",
  "      console.warn('[discovery]', err.message);",
  "    }",
  "  }",
  "  return merged;",
  "}",
  "",
  "module.exports = {",
  "  discoveryEnabled,",
  "  collectAllDiscoveryCandidates,",
  "  collectUfOfficialNewsCandidates: ufOfficial.collectUfOfficialNewsCandidates,",
  "  collectRosterDeltaCandidates: roster.collectRosterDeltaCandidates,",
  "  collectScoutingUpdateCandidates: scouting.collectScoutingUpdateCandidates,",
  "  collectGameZoneCandidates: gameZone.collectGameZoneCandidates,",
  "  collectHeatMoverCandidates: heat.collectHeatMoverCandidates,",
  "  scanRosterDeltas: roster.scanRosterDeltas,",
  "  buildNewsFromRosterEvent: roster.buildNewsFromRosterEvent,",
  "};",
  "",
]);

w("story-memory.js", [
  "/** Phase 3 — 7-day story-unit dedupe. */",
  "const fs = require('fs');",
  "const path = require('path');",
  "const crypto = require('crypto');",
  "const { DATA_DIR } = require('./discovery-core');",
  "const STORY_PATH = path.join(DATA_DIR, 'autoposter-story-memory.json');",
  "const STORY_WINDOW_MS = parseInt(process.env.X_AUTOPOST_STORY_WINDOW_MS || String(7 * 24 * 60 * 60 * 1000), 10);",
  "function storyMemoryEnabled() { return process.env.X_AUTOPOST_STORY_MEMORY !== 'false'; }",
  "function normalizeSlug(raw) { return String(raw || '').trim().toLowerCase(); }",
  "function headlineHash(text) { return crypto.createHash('sha256').update(String(text || '').trim().toLowerCase().slice(0, 120)).digest('hex').slice(0, 12); }",
  "function normalizeStoryArc(c) {",
  "  c = c || {};",
  "  if (c.situation) return String(c.situation).toLowerCase();",
  "  if (c.programNewsType) return 'program:' + c.programNewsType;",
  "  if (c.teamEventType) return 'team:' + c.teamEventType;",
  "  const et = String(c.sourceEventType || c.eventType || '').toLowerCase();",
  "  if (et) return et;",
  "  const text = (c.playerName || '') + ' ' + (c.text || '');",
  "  if (/commit|flip|pledge/i.test(text)) return 'commitment';",
  "  if (/portal|transfer/i.test(text)) return 'portal';",
  "  if (/\\b(ov|uv|visit)\\b/i.test(text)) return 'visit';",
  "  if (/offer/i.test(text)) return 'offer';",
  "  if (/depth chart|injury|roster/i.test(text)) return 'roster';",
  "  if (/hall of fame|hof/i.test(text)) return 'hall_of_fame';",
  "  return 'general';",
  "}",
  "function computeStoryUnitKey(c) {",
  "  if (!c) return null;",
  "  const arc = normalizeStoryArc(c);",
  "  const slug = normalizeSlug(c.playerSlug || c.playerName);",
  "  if (slug) return slug + '|' + arc;",
  "  const headline = (c.validationMeta && c.validationMeta.officialHeadline) || String(c.text || '').split('\\n')[0] || '';",
  "  if (c.programNewsType) return 'program|' + c.programNewsType + '|' + headlineHash(headline);",
  "  return 'story|' + arc + '|' + headlineHash(headline);",
  "}",
  "function readStore() { try { return JSON.parse(fs.readFileSync(STORY_PATH, 'utf8')); } catch { return { entries: [] }; } }",
  "function writeStore(doc) { fs.mkdirSync(path.dirname(STORY_PATH), { recursive: true }); doc.updatedAt = new Date().toISOString(); fs.writeFileSync(STORY_PATH, JSON.stringify(doc, null, 2), 'utf8'); }",
  "function hasRecentStoryUnit(c) {",
  "  if (!storyMemoryEnabled()) return { hit: false };",
  "  const key = computeStoryUnitKey(c);",
  "  if (!key) return { hit: false };",
  "  const cutoff = Date.now() - STORY_WINDOW_MS;",
  "  for (const e of readStore().entries || []) {",
  "    if (e.storyUnitKey !== key) continue;",
  "    if (new Date(e.postedAt || 0).getTime() >= cutoff) return { hit: true, reason: 'story_unit', storyUnitKey: key };",
  "  }",
  "  return { hit: false, storyUnitKey: key };",
  "}",
  "function recordStoryUnit(item) {",
  "  if (!storyMemoryEnabled() || !item) return null;",
  "  const key = computeStoryUnitKey(item);",
  "  if (!key) return null;",
  "  const row = { storyUnitKey: key, storyArc: normalizeStoryArc(item), playerSlug: normalizeSlug(item.playerSlug), source: item.source, tweetId: item.tweetId, postedAt: item.sentAt || new Date().toISOString() };",
  "  const doc = readStore();",
  "  doc.entries = [row, ...(doc.entries || [])].filter((e) => new Date(e.postedAt || 0).getTime() >= Date.now() - STORY_WINDOW_MS).slice(0, 400);",
  "  writeStore(doc);",
  "  return row;",
  "}",
  "function getStoryMemorySummary() {",
  "  const entries = readStore().entries || [];",
  "  return { enabled: storyMemoryEnabled(), recentCount: entries.length, windowMs: STORY_WINDOW_MS };",
  "}",
  "module.exports = { storyMemoryEnabled, normalizeStoryArc, computeStoryUnitKey, hasRecentStoryUnit, recordStoryUnit, getStoryMemorySummary };",
]);

w("topic-memory.js", [
  "/** Phase 3 — player + situation + angle cooldown. */",
  "const fs = require('fs');",
  "const path = require('path');",
  "const { DATA_DIR } = require('./discovery-core');",
  "const TOPIC_PATH = path.join(DATA_DIR, 'autoposter-topic-memory.json');",
  "const TOPIC_WINDOW_MS = parseInt(process.env.X_AUTOPOST_TOPIC_MEMORY_MS || String(48 * 60 * 60 * 1000), 10);",
  "function topicMemoryEnabled() { return process.env.X_AUTOPOST_TOPIC_MEMORY !== 'false'; }",
  "function normalizeSlug(raw) { return String(raw || '').trim().toLowerCase(); }",
  "function extractTopicAngle(c) { const m = (c && c.validationMeta) || {}; return String(m.angle || m.updateType || m.ladderAngle || c.programNewsType || c.teamEventType || c.sourceEventType || c.source || 'general').toLowerCase(); }",
  "function extractSituation(c) { return require('./story-memory').normalizeStoryArc(c); }",
  "function topicKey(c) { const slug = normalizeSlug(c && c.playerSlug); const s = extractSituation(c); const a = extractTopicAngle(c); return slug ? slug + '|' + s + '|' + a : 'program|' + s + '|' + a; }",
  "function readStore() { try { return JSON.parse(fs.readFileSync(TOPIC_PATH, 'utf8')); } catch { return { entries: [] }; } }",
  "function writeStore(doc) { fs.mkdirSync(path.dirname(TOPIC_PATH), { recursive: true }); doc.updatedAt = new Date().toISOString(); fs.writeFileSync(TOPIC_PATH, JSON.stringify(doc, null, 2), 'utf8'); }",
  "function hasRecentTopicAngle(c) {",
  "  if (!topicMemoryEnabled()) return { hit: false };",
  "  const key = topicKey(c);",
  "  const cutoff = Date.now() - TOPIC_WINDOW_MS;",
  "  for (const e of readStore().entries || []) {",
  "    if (e.topicKey === key && new Date(e.usedAt || 0).getTime() >= cutoff) return { hit: true, reason: 'topic_angle', topicKey: key };",
  "  }",
  "  return { hit: false, topicKey: key };",
  "}",
  "function recordTopicUsage(item) {",
  "  if (!topicMemoryEnabled() || !item) return null;",
  "  const row = { topicKey: topicKey(item), playerSlug: normalizeSlug(item.playerSlug), situation: extractSituation(item), angle: extractTopicAngle(item), usedAt: item.sentAt || new Date().toISOString() };",
  "  const doc = readStore();",
  "  doc.entries = [row, ...(doc.entries || [])].filter((e) => new Date(e.usedAt || 0).getTime() >= Date.now() - TOPIC_WINDOW_MS).slice(0, 500);",
  "  writeStore(doc);",
  "  return row;",
  "}",
  "function listRecentAnglesForPlayer(slug, situation) {",
  "  const s = normalizeSlug(slug);",
  "  const cutoff = Date.now() - TOPIC_WINDOW_MS;",
  "  return (readStore().entries || []).filter((e) => s && String(e.topicKey || '').startsWith(s + '|') && (!situation || e.situation === situation) && new Date(e.usedAt || 0).getTime() >= cutoff).map((e) => e.angle);",
  "}",
  "function getTopicMemorySummary() {",
  "  const entries = readStore().entries || [];",
  "  return { enabled: topicMemoryEnabled(), recentCount: entries.length, windowMs: TOPIC_WINDOW_MS };",
  "}",
  "module.exports = { topicMemoryEnabled, extractTopicAngle, topicKey, hasRecentTopicAngle, recordTopicUsage, listRecentAnglesForPlayer, getTopicMemorySummary };",
]);

w("evergreen-library.js", [
  "/** Phase 3 — curated UF football evergreen posts. */",
  "const { intelFingerprint } = require('../commit-fingerprint');",
  "const { readJson, writeJson, SITE_URL } = require('./discovery-core');",
  "const EVERGREEN_PATH = require('path').join(require('path').join(__dirname, '..', '..', 'data', 'x'), 'autoposter-evergreen.json');",
  "const SNAPSHOT_PATH = require('path').join(require('path').join(__dirname, '..', '..', 'data', 'x'), 'autoposter-evergreen-snapshot.json');",
  "function evergreenEnabled() { return process.env.X_AUTOPOST_EVERGREEN_ENABLED !== 'false'; }",
  "function defaultLibrary() { return { version: 1, items: [",
  "  { id: 'swamp-history', topic: 'program', angle: 'history', headline: 'The Swamp — one of college football\\'s loudest venues.', context: 'Ben Hill Griffin Stadium has anchored Florida football since 1930 — a home-field edge SEC foes respect.', sourceUrl: 'https://floridagators.com/sports/football' },",
  "  { id: 'uf-hof', topic: 'program', angle: 'hall_of_fame', headline: 'Florida football Hall of Fame tradition runs deep.', context: 'Legends built this program — roster and recruiting still writing the next chapter.', sourceUrl: 'https://floridagators.com/sports/football' },",
  "  { id: 'futurecast-lab', topic: 'recruiting', angle: 'analysis', headline: 'FutureCast Lab — UF probability, movement, and fit scores.', context: 'GatorVault models commit likelihood and 7-day RPM movement for every top target.', sourceUrl: 'https://gatorvaultinsider.com/vault/futurecast' },",
  "  { id: 'depth-chart', topic: 'team', angle: 'roster', headline: 'Depth chart intel — spring moves matter for fall.', context: 'Position battles and returns shape the roster — GatorVault tracks Florida live.', sourceUrl: 'https://gatorvaultinsider.com/vault/depth-chart' },",
  "  { id: 'scout-db', topic: 'recruiting', angle: 'scouting', headline: 'GV Scout Database — verified reads on targets and roster.', context: 'Analyst evaluations feed the board — context rankings alone cannot provide.', sourceUrl: 'https://gatorvaultinsider.com/vault/scouting' },",
  "  { id: 'game-week', topic: 'team', angle: 'schedule', headline: 'Game Week — schedule, spreads, and matchup intel.', context: 'Every Florida matchup with lines and context as the season approaches.', sourceUrl: 'https://gatorvaultinsider.com/vault/game-week' },",
  "  { id: 'portal-watch', topic: 'portal', angle: 'portal', headline: 'Portal intel — who fits Florida\\'s roster plan.', context: 'Transfer movement is roster construction — GatorVault tracks portal likelihood and UF fit.', sourceUrl: 'https://gatorvaultinsider.com/vault/portal' },",
  "]}; }",
  "function loadLibrary() { const doc = readJson(EVERGREEN_PATH, null); if (doc && doc.items && doc.items.length) return doc; const seeded = defaultLibrary(); writeJson(EVERGREEN_PATH, seeded); return seeded; }",
  "function buildEvergreenCandidate(item) {",
  "  if (!item || !item.headline) return null;",
  "  const identity = 'Florida Gators Football';",
  "  const text = [identity, item.headline, item.context, item.sourceUrl || SITE_URL].join('\\n');",
  "  return { text, category: 'news', topic: item.topic || 'program', urgencyLabel: 'analysis', sourceEventType: 'evergreen', triggerType: item.topic === 'program' ? 'program_news' : item.topic === 'team' ? 'team_event' : null, programNewsType: item.angle === 'hall_of_fame' ? 'hall_of_fame' : item.angle === 'history' ? 'history' : 'program_update', sources: [{ label: 'GatorVault', url: item.sourceUrl || SITE_URL }], source: 'auto:evergreen', intelFingerprint: intelFingerprint(item.id, 'evergreen', new Date().toISOString().slice(0, 10)), sourceEventCreatedAt: new Date().toISOString(), identityConfirmed: true, validationMeta: { programNews: true, evergreen: true, eliteCompose: true, angle: item.angle }, templateBlocks: { identity, context: item.headline, insider: item.context } };",
  "}",
  "function collectEvergreenCandidates(opts) { opts = opts || {}; if (!evergreenEnabled()) return []; const lib = loadLibrary(); const snapshot = readJson(SNAPSHOT_PATH, { posted: {} }); const out = []; for (const item of lib.items || []) { if (out.length >= (opts.limit || 4)) break; if (!opts.forcePost && snapshot.posted[item.id]) continue; const row = buildEvergreenCandidate(item); if (row) { out.push(row); snapshot.posted[item.id] = new Date().toISOString(); } } if (out.length) writeJson(SNAPSHOT_PATH, snapshot); return out; }",
  "module.exports = { evergreenEnabled, collectEvergreenCandidates, buildEvergreenCandidate };",
]);

w("performance-tracker.js", [
  "/** Phase 3 — post-type performance memory. */",
  "const fs = require('fs');",
  "const path = require('path');",
  "const PERF_PATH = path.join(__dirname, '..', '..', 'data', 'x', 'autoposter-performance.json');",
  "function performanceLoopEnabled() { return process.env.X_AUTOPOST_PERFORMANCE_LOOP !== 'false'; }",
  "function dimensionsFromItem(item) { return { source: String(item && item.source || 'unknown').slice(0, 64), topic: String(item && item.topic || 'general').slice(0, 32), sourceEventType: String(item && item.sourceEventType || 'news').slice(0, 32) }; }",
  "function dimKey(d) { return d.source + '|' + d.topic + '|' + d.sourceEventType; }",
  "function readStore() { try { return JSON.parse(fs.readFileSync(PERF_PATH, 'utf8')); } catch { return { totals: {}, recent: [] }; } }",
  "function writeStore(doc) { fs.mkdirSync(path.dirname(PERF_PATH), { recursive: true }); doc.updatedAt = new Date().toISOString(); fs.writeFileSync(PERF_PATH, JSON.stringify(doc, null, 2), 'utf8'); }",
  "function recordPostPerformance(item) { if (!performanceLoopEnabled() || !item) return null; const d = dimensionsFromItem(item); const key = dimKey(d); const doc = readStore(); if (!doc.totals[key]) doc.totals[key] = { count: 0 }; doc.totals[key].count += 1; doc.totals[key].lastPostedAt = item.sentAt || new Date().toISOString(); writeStore(doc); return { key, count: doc.totals[key].count }; }",
  "function candidatePerformanceBoost(c) { if (!performanceLoopEnabled()) return 0; const key = dimKey(dimensionsFromItem(c)); const row = readStore().totals[key]; if (!row || !row.count) return 0; const hours = (Date.now() - new Date(row.lastPostedAt || 0).getTime()) / 3600000; if (hours < 6) return -3; if (row.count >= 8) return -1; return 0; }",
  "function getPerformanceSummary() {",
  "  const totals = readStore().totals || {};",
  "  const topTypes = Object.entries(totals).sort((a, b) => (b[1].count || 0) - (a[1].count || 0)).slice(0, 8).map(([key, row]) => ({ key, count: row.count || 0, lastPostedAt: row.lastPostedAt || null }));",
  "  return { enabled: performanceLoopEnabled(), typeCount: Object.keys(totals).length, topTypes };",
  "}",
  "module.exports = { performanceLoopEnabled, recordPostPerformance, candidatePerformanceBoost, getPerformanceSummary };",
]);

w("research-ladder.js", [
  "/** Phase 3 — dig deeper when gates block enqueue. */",
  "const { SITE_URL } = require('./discovery-core');",
  "const { intelFingerprint } = require('../commit-fingerprint');",
  "function ladderEnabled() { return process.env.X_AUTOPOST_RESEARCH_LADDER !== 'false'; }",
  "const ANGLES = ['fit_analysis', 'visit_intel', 'competition', 'scheme_fit', 'momentum'];",
  "function pickAngle(used) { const set = new Set((used || []).map(String)); for (const a of ANGLES) { if (!set.has(a)) return a; } return ANGLES[0]; }",
  "async function buildResearchLadderCandidate(raw, reason) {",
  "  if (!ladderEnabled() || !raw) return null;",
  "  if (!['gm2_filter', 'quality_gate', 'policy', 'topic_angle'].includes(reason)) return null;",
  "  const slug = raw.playerSlug; const name = raw.playerName;",
  "  if (slug || name) {",
  "    const topicMemory = require('./topic-memory');",
  "    const story = require('./story-memory');",
  "    const angle = pickAngle(topicMemory.listRecentAnglesForPlayer(slug || name, story.normalizeStoryArc(raw)));",
  "    let insider = '';",
  "    try { const research = require('../x-autoposter-elite-research'); const pack = await research.researchUpdate({ playerSlug: slug, playerName: name, beatText: raw.text || '', eventType: raw.sourceEventType || 'recruiting' }); insider = String(pack && pack.insiderLine || pack && pack.contextLine || '').trim(); } catch {}",
  "    const identity = name || 'Florida target';",
  "    const contextLine = 'GatorVault dig-deeper — ' + angle.replace(/_/g, ' ') + ' on the Florida board.';",
  "    const url = slug ? SITE_URL + '/vault/futurecast/player/' + slug : SITE_URL;",
  "    const text = [identity, contextLine, insider || 'Full intel on FutureCast.', url].join('\\n');",
  "    return Object.assign({}, raw, { text, source: 'auto:research-ladder', intelFingerprint: intelFingerprint(slug || name, 'ladder_' + angle, new Date().toISOString().slice(0, 10)), validationMeta: Object.assign({}, raw.validationMeta || {}, { eliteCompose: true, ladderAngle: angle, researchLadder: true }), templateBlocks: { identity, context: contextLine, insider: insider || 'Full intel on FutureCast.' } });",
  "  }",
  "  if (reason === 'quality_gate' || reason === 'gm2_filter') {",
  "    const rows = require('./evergreen-library').collectEvergreenCandidates({ limit: 1, forcePost: true });",
  "    if (rows[0]) return rows[0];",
  "  }",
  "  return null;",
  "}",
  "async function buildAlternateFromResearch(item) { return buildResearchLadderCandidate(item, 'quality_gate'); }",
  "module.exports = { ladderEnabled, buildResearchLadderCandidate, buildAlternateFromResearch };",
]);

w("phase3-index.js", [
  "/** Phase 3 barrel — story/topic memory, ladder, evergreen, performance. */",
  "const storyMemory = require('./story-memory');",
  "const topicMemory = require('./topic-memory');",
  "const researchLadder = require('./research-ladder');",
  "const evergreenLibrary = require('./evergreen-library');",
  "const performanceTracker = require('./performance-tracker');",
  "function phase3Enabled() { return process.env.X_AUTOPOST_PHASE3_ENABLED !== 'false'; }",
  "function guardCandidateMemory(c) {",
  "  if (!phase3Enabled()) return { ok: true };",
  "  const story = storyMemory.hasRecentStoryUnit(c);",
  "  if (story.hit) return { ok: false, reason: 'story_dedupe', detail: story };",
  "  const topic = topicMemory.hasRecentTopicAngle(c);",
  "  if (topic.hit) return { ok: false, reason: 'topic_angle', detail: topic };",
  "  return { ok: true };",
  "}",
  "function recordPostMemory(item) {",
  "  if (!phase3Enabled()) return;",
  "  try { storyMemory.recordStoryUnit(item); } catch {}",
  "  try { topicMemory.recordTopicUsage(item); } catch {}",
  "  try { performanceTracker.recordPostPerformance(item); } catch {}",
  "}",
  "module.exports = { phase3Enabled, storyMemory, topicMemory, researchLadder, evergreenLibrary, performanceTracker, guardCandidateMemory, recordPostMemory };",
]);

w("discovery-heat.js", [
  "/** Phase 4 — FutureCast heat mover discovery. */",
  "const { intelFingerprint } = require('../commit-fingerprint');",
  "const { SITE_URL } = require('./discovery-core');",
  "function heatDiscoveryEnabled() { return process.env.X_AUTOPOST_HEAT_DISCOVERY !== 'false'; }",
  "async function collectHeatMoverCandidates(opts) {",
  "  opts = opts || {};",
  "  if (!heatDiscoveryEnabled()) return [];",
  "  const limit = opts.limit || parseInt(process.env.X_AUTOPOST_HEAT_MOVER_LIMIT || '5', 10);",
  "  const out = [];",
  "  try {",
  "    const { buildHeatCheck } = require('../heat-check-store');",
  "    const heat = await buildHeatCheck();",
  "    for (const row of (heat && heat.rising || []).slice(0, limit)) {",
  "      if (!row || !row.name) continue;",
  "      const slug = row.slug || String(row.name).toLowerCase().replace(/\\s+/g, '-');",
  "      const fp = intelFingerprint(slug, 'heat_mover', new Date().toISOString().slice(0, 10));",
  "      const classYear = row.classYear ? row.classYear + ' ' : '';",
  "      const pos = row.pos ? ' ' + row.pos : '';",
  "      const identity = (classYear + row.name + pos).trim();",
  "      const text = [identity, 'GatorVault Heat Check — RPM momentum building on the Florida board.', 'Full prediction + visit intel ↓', SITE_URL + '/vault/futurecast/player/' + slug].join('\\n');",
  "      out.push({ text, category: 'news', topic: 'recruiting', urgencyLabel: 'analysis', sourceEventType: 'heat_mover', sources: [{ label: 'GatorVault Heat Check', url: SITE_URL }], source: 'auto:heat-mover', intelFingerprint: fp, playerName: row.name, playerSlug: slug, sourceEventCreatedAt: new Date().toISOString(), identityConfirmed: true, validationMeta: { eliteCompose: true, heatMover: true }, templateBlocks: { identity, context: 'GatorVault Heat Check — RPM momentum building on the Florida board.', insider: 'Full prediction + visit intel on FutureCast.' } });",
  "    }",
  "  } catch (err) { console.warn('[discovery-heat]', err.message); }",
  "  return out;",
  "}",
  "module.exports = { heatDiscoveryEnabled, collectHeatMoverCandidates };",
]);

w("time-bucket.js", [
  "/** Phase 4 — ET time-bucket topic bias for daily posting rhythm. */",
  "const TZ = process.env.X_AUTOPOST_NIGHT_TZ || 'America/New_York';",
  "function timeBucketEnabled() { return process.env.X_AUTOPOST_TIME_BUCKETS !== 'false'; }",
  "function getEstHour(date) {",
  "  date = date || new Date();",
  "  try {",
  "    const parts = new Intl.DateTimeFormat('en-US', { timeZone: TZ, hour: 'numeric', hour12: false }).formatToParts(date);",
  "    return parseInt(parts.find((p) => p.type === 'hour').value || '12', 10);",
  "  } catch { return date.getUTCHours() - 5; }",
  "}",
  "function getTimeBucket(date) {",
  "  const h = getEstHour(date);",
  "  if (h >= 0 && h < 6) return 'night';",
  "  if (h >= 6 && h < 10) return 'morning';",
  "  if (h >= 10 && h < 18) return 'day';",
  "  if (h >= 18 && h < 23) return 'evening';",
  "  return 'night';",
  "}",
  "const BUCKET_BOOSTS = {",
  "  morning: { program_news: -2, uf_official_news: -2, team_event: -2, roster_delta: -2, evergreen: -1 },",
  "  day: { commitment: -2, portal: -2, beat_intel: -1, heat_mover: -2, scouting_update: -1, research_ladder: -1 },",
  "  evening: { game_week: -2, article: -1, heat_mover: -1, recruiting_momentum: -1 },",
  "  night: { commitment: -1, portal: -1 },",
  "};",
  "function classifyCandidateBucketTopic(raw) {",
  "  if (raw && (raw.triggerType === 'program_news' || raw.programNewsType)) return 'program_news';",
  "  if (raw && (raw.triggerType === 'team_event' || raw.teamEventType)) return 'team_event';",
  "  if (raw && raw.source === 'auto:uf-official-news') return 'uf_official_news';",
  "  if (raw && raw.source === 'auto:roster-delta') return 'roster_delta';",
  "  if (raw && raw.source === 'auto:game-zone') return 'game_week';",
  "  if (raw && raw.source === 'auto:scouting-update') return 'scouting_update';",
  "  if (raw && raw.source === 'auto:heat-mover') return 'heat_mover';",
  "  if (raw && raw.source === 'auto:evergreen') return 'evergreen';",
  "  const et = String(raw && raw.sourceEventType || '').toLowerCase();",
  "  if (/commit|flip/.test(et)) return 'commitment';",
  "  if (/portal/.test(et)) return 'portal';",
  "  if (et === 'recruiting_momentum') return 'recruiting_momentum';",
  "  if (raw && (raw.source === 'auto:article' || et === 'article')) return 'article';",
  "  if (String(raw && raw.source || '').includes('beat')) return 'beat_intel';",
  "  return 'general';",
  "}",
  "function candidateTimeBucketBoost(raw, bucket) {",
  "  if (!timeBucketEnabled()) return 0;",
  "  const map = BUCKET_BOOSTS[bucket || getTimeBucket()] || {};",
  "  return map[classifyCandidateBucketTopic(raw)] || 0;",
  "}",
  "module.exports = { timeBucketEnabled, getEstHour, getTimeBucket, classifyCandidateBucketTopic, candidateTimeBucketBoost };",
]);

w("phase4-index.js", [
  "/** Phase 4 barrel — rhythm scheduling + ops intel snapshot. */",
  "const timeBucket = require('./time-bucket');",
  "function phase4Enabled() { return process.env.X_AUTOPOST_PHASE4_ENABLED !== 'false'; }",
  "function getOperationalIntel() {",
  "  const snap = { phase4Enabled: phase4Enabled(), timeBucket: timeBucket.getTimeBucket(), timeBucketsEnabled: timeBucket.timeBucketEnabled(), heatDiscovery: process.env.X_AUTOPOST_HEAT_DISCOVERY !== 'false' };",
  "  try {",
  "    const p3 = require('./phase3-index');",
  "    snap.phase3Enabled = p3.phase3Enabled();",
  "    snap.storyMemory = p3.storyMemory.getStoryMemorySummary();",
  "    snap.topicMemory = p3.topicMemory.getTopicMemorySummary();",
  "    snap.performance = p3.performanceTracker.getPerformanceSummary();",
  "  } catch { snap.phase3Enabled = false; }",
  "  return snap;",
  "}",
  "module.exports = { phase4Enabled, timeBucket, getOperationalIntel };",
]);

