/**
 * Flat sitemap rewrites + legacy redirects (CJS for routes.js / Netlify).
 */

function subRouteRewrites(prefix, exportPath) {
  return [
    { from: prefix, to: exportPath, status: 200 },
    { from: `${prefix}/`, to: exportPath, status: 200 },
    { from: `${prefix}/*`, to: exportPath, status: 200 },
  ];
}

/** Static-export SPA rewrites for canonical product routes. */
const SITE_REACT_REWRITES = [
  { from: '/', to: '/index.html', status: 200 },
  ...subRouteRewrites('/recruiting/player', '/recruiting/player/index.html'),
  ...subRouteRewrites('/recruiting', '/recruiting/index.html'),
  ...subRouteRewrites('/futurecast/player', '/futurecast/player/index.html'),
  ...subRouteRewrites('/futurecast/trending', '/futurecast/trending/index.html'),
  ...subRouteRewrites('/futurecast/movement', '/futurecast/movement/index.html'),
  ...subRouteRewrites('/futurecast/staff', '/futurecast/staff/index.html'),
  ...subRouteRewrites('/futurecast', '/futurecast/index.html'),
  ...subRouteRewrites('/team/player', '/team/player/index.html'),
  ...subRouteRewrites('/team', '/team/index.html'),
  ...subRouteRewrites('/gator-nation-live', '/gator-nation-live/index.html'),
  ...subRouteRewrites('/schedule/season', '/schedule/season/index.html'),
  ...subRouteRewrites('/schedule', '/schedule/index.html'),
  ...subRouteRewrites('/film-room', '/film-room/index.html'),
  { from: '/game-week/*', to: '/game-week/game/index.html', status: 200 },
  ...subRouteRewrites('/game-week', '/game-week/index.html'),
  ...subRouteRewrites('/live-scores', '/live-scores/index.html'),
  { from: '/articles/*', to: '/articles/detail/index.html', status: 200 },
  ...subRouteRewrites('/articles', '/articles/index.html'),
  { from: '/community/thread/*', to: '/community/thread/index.html', status: 200 },
  ...subRouteRewrites('/community', '/community/index.html'),
  { from: '/game-zone/*', to: '/game-zone/game/index.html', status: 200 },
  ...subRouteRewrites('/game-zone', '/game-zone/index.html'),
  ...subRouteRewrites('/nil', '/nil/index.html'),
];

/** Legacy /vault/* and aliases → flat site paths (301). */
const VAULT_TO_SITE_REDIRECTS = [
  { from: '/vault', to: '/', status: 301 },
  { from: '/vault/', to: '/', status: 301 },
  { from: '/vault/recruiting', to: '/recruiting', status: 301 },
  { from: '/vault/recruiting/*', to: '/recruiting/:splat', status: 301 },
  { from: '/vault/futurecast', to: '/futurecast', status: 301 },
  { from: '/vault/futurecast/*', to: '/futurecast/:splat', status: 301 },
  { from: '/vault/team', to: '/team', status: 301 },
  { from: '/vault/team/*', to: '/team/:splat', status: 301 },
  { from: '/vault/live', to: '/gator-nation-live', status: 301 },
  { from: '/vault/live/*', to: '/gator-nation-live/:splat', status: 301 },
  { from: '/vault/live-feed', to: '/gator-nation-live', status: 301 },
  { from: '/vault/live-feed/*', to: '/gator-nation-live/:splat', status: 301 },
  { from: '/vault/schedule', to: '/schedule', status: 301 },
  { from: '/vault/schedule/*', to: '/schedule/:splat', status: 301 },
  { from: '/vault/film-room', to: '/film-room', status: 301 },
  { from: '/vault/film-room/*', to: '/film-room/:splat', status: 301 },
  { from: '/vault/game-week', to: '/game-week', status: 301 },
  { from: '/vault/game-week/*', to: '/game-week/:splat', status: 301 },
  { from: '/vault/live-scores', to: '/live-scores', status: 301 },
  { from: '/vault/live-scores/*', to: '/live-scores/:splat', status: 301 },
  { from: '/vault/articles', to: '/articles', status: 301 },
  { from: '/vault/articles/*', to: '/articles/:splat', status: 301 },
  { from: '/vault/insider', to: '/articles', status: 301 },
  { from: '/vault/insider/*', to: '/articles/:splat', status: 301 },
  { from: '/vault/community', to: '/community', status: 301 },
  { from: '/vault/community/*', to: '/community/:splat', status: 301 },
  { from: '/vault/game-zone', to: '/game-zone', status: 301 },
  { from: '/vault/game-zone/*', to: '/game-zone/:splat', status: 301 },
  { from: '/vault/nil', to: '/nil', status: 301 },
  { from: '/vault/nil/*', to: '/nil/:splat', status: 301 },
  { from: '/vault/players/*', to: '/team/player/:splat', status: 301 },
  { from: '/gatornation-live', to: '/gator-nation-live', status: 301 },
  { from: '/gatornation-live/*', to: '/gator-nation-live/:splat', status: 301 },
  { from: '/recruiting-hub', to: '/recruiting', status: 301 },
  { from: '/recruiting-hub/*', to: '/recruiting/:splat', status: 301 },
  { from: '/futurecast/trending', to: '/futurecast#trending', status: 301 },
  { from: '/futurecast/trending/', to: '/futurecast#trending', status: 301 },
  { from: '/futurecast/movement', to: '/futurecast#movement', status: 301 },
  { from: '/futurecast/movement/', to: '/futurecast#movement', status: 301 },
  { from: '/futurecast/staff', to: '/futurecast#signals', status: 301 },
  { from: '/futurecast/staff/', to: '/futurecast#signals', status: 301 },
  { from: '/futurecast/trending-board', to: '/futurecast#trending', status: 301 },
  { from: '/futurecast/trending-board/*', to: '/futurecast#trending', status: 301 },
  { from: '/futurecast/movement-intel', to: '/futurecast#movement', status: 301 },
  { from: '/futurecast/movement-intel/*', to: '/futurecast#movement', status: 301 },
  { from: '/futurecast/staff-notes', to: '/futurecast#signals', status: 301 },
  { from: '/futurecast/staff-notes/*', to: '/futurecast#signals', status: 301 },
  { from: '/futurecast/stock', to: '/futurecast#master-board', status: 301 },
  { from: '/futurecast/stock/*', to: '/futurecast#master-board', status: 301 },
  { from: '/futurecast/snapshots', to: '/futurecast#overview', status: 301 },
  { from: '/futurecast/snapshots/*', to: '/futurecast#overview', status: 301 },
  { from: '/futurecast/alerts', to: '/futurecast#feed', status: 301 },
  { from: '/futurecast/alerts/*', to: '/futurecast#feed', status: 301 },
];

const REQUIRED_SITE_EXPORTS = [
  'index.html',
  'recruiting/index.html',
  'recruiting/player/index.html',
  'futurecast/index.html',
  'futurecast/player/index.html',
  'futurecast/trending/index.html',
  'futurecast/movement/index.html',
  'futurecast/staff/index.html',
  'team/index.html',
  'team/player/index.html',
  'gator-nation-live/index.html',
  'schedule/index.html',
  'schedule/season/index.html',
  'film-room/index.html',
  'game-week/index.html',
  'game-week/game/index.html',
  'live-scores/index.html',
  'articles/index.html',
  'articles/detail/index.html',
  'community/index.html',
  'community/thread/index.html',
  'game-zone/index.html',
  'game-zone/game/index.html',
  'nil/index.html',
  'welcome/index.html',
  'insider/index.html',
  'join/index.html',
];

module.exports = {
  SITE_REACT_REWRITES,
  VAULT_TO_SITE_REDIRECTS,
  REQUIRED_SITE_EXPORTS,
  subRouteRewrites,
};
